--- Makefile.orig
+++ Makefile
@@ -101,8 +101,8 @@
 
 .include <bsd.port.pre.mk>
 
-.if ${OPSYS} != FreeBSD
-IGNORE=		is only for FreeBSD
+.if ${OPSYS} != FreeBSD && ${OPSYS} != DragonFly
+IGNORE=		is only for FreeBSD and DragonFly BSD
 .endif
 
 .if ${ARCH} == powerpc
